### ISSUE TITLE
Fix dates and operation duration

### ISSUE THREAD

**Issue by TheAlexLichter** [albionstatus/albionstatus-website#14]
When switching from moment to luxon, I’ve accidentally forgot to correctly change the formatting on the main page 
![D342053B-C51F-4A82-AFA0-4CE3D69050E2](https://user-images.githubusercontent.com/640208/66073174-e301b980-e556-11e9-8d31-502268d191d0.jpeg)

## Tasks

* Change the “operating since” date to a common date format
* Change the „already“ date to duration word format (eg “already 2 years, 5 months and 3 days”)

**Comment by vanya829** [comment]
I can fix this one
